language: cpp

os:
    - linux
    - osx

env:
    - CONFIG=Release
    - CONFIG=Debug

compiler:
    - gcc
    - clang

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
          osx_image: xcode7.2

before install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi

script:
    - make all
